### ISSUE TITLE
GetDayData 报错

### ISSUE THREAD

**Issue by xxm1988** [xjkj123/SharesData#1]
ShareClass().GetDayData(code='600000',start='1980-01-01',end="",zs=False)

>>> ShareClass().GetDayData(code='600000',start='1991-01-01',end="",zs=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ShareData.py", line 85, in GetDayData
    dfgb = ShareClass().GetGuben(code)
  File "ShareData.py", line 321, in GetGuben
    x = BeautifulSoup(ret.text, "html.parser")
  File "/usr/lib64/python2.6/site-packages/bs4/__init__.py", line 228, in __init__
    self._feed()
  File "/usr/lib64/python2.6/site-packages/bs4/__init__.py", line 289, in _feed
    self.builder.feed(self.markup)
  File "/usr/lib64/python2.6/site-packages/bs4/builder/_htmlparser.py", line 219, in feed
    raise e
HTMLParser.HTMLParseError: malformed start tag, at line 262, column 59

**Comment by xxm1988** [comment]
搞定了，改成html5lib方式就好了
